### PR TITLE
Interns/gracet9182/39629 config page

### PR DESCRIPTION
**Pull request by gracet9182**
# What is this? 
* Remove the scroll bars in the config page
* Update string 
* Fit the background for dark mode

# Demo 
Screenshot 2021-08-10 083522
Screenshot 2021-08-10 083439

### CODE REVIEW

**Review by omersayshi — APPROVED** [review]

**Comment by lhao03** [comment]
Uh my app is white now
image

**Review by lhao03 — DISMISSED** [review]
image
uh my app is pure white now

**Comment by gracet9182** [comment]
> image
> uh my app is pure white now

ee8cd46431108840f9880a818541cc9563ff146c

**Review by lhao03 — APPROVED** [review]
noice 
\^o^/

**Pull request merged**
