### PR TITLE
AB#38568 add azure pipelines 

### PR DESCRIPTION
**Pull request by acchiang**
Adds CI to the repository, runs npm scripts from the package.lock in ToolkitApp/tab. 

Pipeline: https://dev.azure.com/microsoftgarage/Intern%20GitHub/_build?definitionId=352

### CODE REVIEW

**Comment by lhao03** [comment]
Does it lint? Or can we add a linter?

**Comment by acchiang** [comment]
@lhao03 nope none installed afaik, yes we can add a linter! 

edit: @lhao03 i added npm run lint to the pipeline!

**Comment by acchiang** [comment]
@lhao03 and team, the linter is pointing out quite a few flaws with our codebase, anyone have ideas on who to bypass these linting errors? 
https://dev.azure.com/microsoftgarage/Intern%20GitHub/_build/results?buildId=38019&view=logs&j=cb4db6dd-e658-55b7-b337-8761517bc1a3&t=80fb99b8-70bb-54f3-a46b-2738c1a5aec3

**Comment by lhao03** [comment]
It's good that it's finding a lot of errors (our code is quite messy), so we can fix them now

**Comment by csyan5** [comment]
@acchiang I went through the list of linter errors and seems there're valid. Could we resolve those errors and re-run the this pipeline?

**Comment by lhao03** [comment]
@acchiang, I can fix them in a PR! Or just push to this branch?

**Review by lhao03 — APPROVED** [review]
Approving and merging in after I fix the current linting errors, because our PRs have alot of linting errors and wanna catch them before they are merged in (and to fix our interns/dev branch too.) Thanks for this Allison! (～￣▽￣)～🙌

**Comment by lhao03** [comment]
I added "react/no-unescaped-entities": 0 to rules because I will fix it in the future (And it's not that important?) Thoughts @acchiang ? I'm not sure the severity of this error.

**Comment by lhao03** [comment]
Merging for now, but we can open another PR to discuss linting rules!

**Pull request merged**
