### PR TITLE
AB#39520 Updated app name and descriptions in manifest.json

### PR DESCRIPTION
**Pull request by jerryxihe**
ADO Board Link: [Task #39520](https://dev.azure.com/microsoftgarage/Intern%20GitHub/_workitems/edit/39520)

## Overview
* We wanted to update the app name and descriptions that appear in the pop-up when you're first uploading the app to Teams.
* Copied Teams app deployment documentation from [here](https://microsoft.sharepoint.com/teams/GarageInternship/_layouts/15/Doc.aspx?sourcedoc={36eb6c54-19b7-4940-ab2f-2f9d6a3dcc82}&action=edit&wd=target%28Project%20Structures.one%7C23306f43-eb03-478d-a22d-e554b4d30dc4%2FDeploying%20teams%20app%7C6f7d6e99-067f-48c5-8a53-2c94d1dc7382%2F%29) into `contributions.md`
### Demo

image

image

## Testing Instructions
* Follow steps 2 through 5 in `contributions.md`. After step 5, you should see a pop-up with the new name and descriptions.
* After uploading the app, you can go to the `About` tab in the app to see the description again.

### CODE REVIEW

**Review by lhao03 — APPROVED** [review]
nice! o(*^＠^*)o

i had to change my version number because i was updating the app because the app id already existed and updates need different version numbers
image

**Comment by omersayshi** [comment]
Might as well change the Azure app id to the new one we made for the Teams app '09dbe221-5dfe-4c5b-8860-49b398ee5052'

**Review by gracet9182 — APPROVED** [review]
nice

**Comment by jerryxihe** [comment]
> Might as well change the Azure app id to the new one we made for the Teams app '09dbe221-5dfe-4c5b-8860-49b398ee5052'

4ef12e24bb8bab3d52e9f22f97bec03fc7c90e33

**Review by omersayshi — APPROVED** [review]
looks great

**Pull request merged**
